FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y curl sudo

RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/David0922/eggless-omelette/main/provision/provision-dev-container.sh)"

CMD ["/usr/sbin/sshd", "-D"]
