services:
  backend:
    build: ./backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      certonly:
        condition: service_completed_successfully

  certonly:
    build: ./certonly
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.certbot/letsencrypt:/etc/letsencrypt
