# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrantfile api/syntax version
# don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$VM_NAME = "devbox"

Vagrant.configure("2") do |config|
  config.vm.define "#{$VM_NAME}" do |devbox|
    # ubuntu 20.04 LTS
    devbox.vm.box = "ubuntu/focal64"

    devbox.vm.hostname = $VM_NAME

    devbox.vm.network "private_network", type: "dhcp"

    devbox.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
    end

    devbox.vm.synced_folder "/david/tmp", "/david-host/tmp", type: "nfs"
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
