# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrantfile api/syntax version
# don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$VM_ID = ''
$VM_NAME = "devbox-#{$VM_ID}"

Vagrant.configure('2') do |config|
  config.vm.define "#{$VM_NAME}" do |devbox|
    # ubuntu 20.04 LTS
    # devbox.vm.box = 'ubuntu/focal64'

    # ubuntu 22.04 LTS
    devbox.vm.box = 'ubuntu/jammy64'

    # vagrant plugin install vagrant-disksize
    config.disksize.size = '80GB'

    devbox.vm.hostname = $VM_NAME

    devbox.vm.network 'private_network', type: 'dhcp'
    # devbox.vm.network 'public_network', type: 'dhcp'

    devbox.vm.provider 'virtualbox' do |v|
      v.cpus = 4
      v.memory = 8192

      # v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end

    # devbox.vm.synced_folder '/david/devbox/tmp', '/mnt-host/tmp', type: 'nfs'
    # devbox.vm.synced_folder '/david/devbox/tmp', '/mnt-host/tmp', type: 'nfs', mount_options: ['tcp']
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = false
  end
end
