services:
  nginx:
    build: ./nginx
    ports:
      - 8080:8080
    networks:
      - internet
      - no-internet
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      # - ./.db:/database
      - /path/to/root:/srv
    networks:
      - no-internet
networks:
  internet: {}
  no-internet:
    internal: true
