cc_library(
    name = "calc_cc_grpc",
    srcs = glob(["calculator*.cc"]),
    hdrs = glob(["calculator*.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "@grpc",
        "@protobuf",
    ],
)
