apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-me
  labels:
    app: curl-me
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curl-me
  template:
    metadata:
      labels:
        app: curl-me
    spec:
      containers:
        - name: curl-me
          image: 'localhost:32000/curl-me'
          ports:
            - containerPort: 8080
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: curl-me
spec:
  type: NodePort
  selector:
    app: curl-me
  ports:
    # nodePort:   a static port assigned on each node
    # port:       port exposed internally in the ClusterIP
    # targetPort: the container port to send requests to
    - nodePort: 30001 # curl HOST_IP:nodePort
      port: 3000 # curl CLUSTER_IP:port
      targetPort: 8080
