load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "crow",
    build_file = "crow.BUILD",
    remote = "https://github.com/CrowCpp/Crow",
    tag = "v1.0+4",
)

new_git_repository(
    name = "fmt",
    build_file = "fmt.BUILD",
    remote = "https://github.com/fmtlib/fmt",
    tag = "9.0.0",
)
