cc_library(
    name = "big_int",
    hdrs = ["big_int.h"],
)

cc_test(
    name = "big_int_test",
    srcs = ["big_int_test.cc"],
    deps = [
        "big_int",
        "@googletest//:gtest_main",
    ],
)
